### ISSUE TITLE
Suggestion for the discount code list

### ISSUE THREAD

**Issue by faselunare** [OFFLINE-GmbH/oc-mall-plugin#312]
In the file models/discount/columns.yml
add these lines to make easy copy and paste the discount code without editing the discount

```
code:
        label: 'offline.mall::lang.discounts.code'
        type: text
        searchable: true
        sortable: true
        clickable: false
```
