### ISSUE TITLE
[IDEA] Provide `october.yaml` file to enable a quick start

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-mall-plugin#685]
Hi,

something that just came to my mind as I quickly wanted to install the plugin: Provide an `october.yaml` for the Bootstrapper as part of this repository or the documentation. That would significantly speed up the process of just getting an October installation with Mall isntalled. Here is my file that I came up with so far:

```yaml
app:
    name: mall           # Give this project a unique name
    url: http://mall.test
    locale: en
    debug: true

cms:
    theme: oc-mall-theme (https://github.com/OFFLINE-GmbH/oc-mall-theme.git)
    edgeUpdates: false
    disableCoreUpdates: false
    enableSafeMode: false

database:
    connection: mysql
    host: localhost
    port: 3306
    username: mall
    password: mall
    database: mall

plugins:
    - RainLab.User
    - RainLab.Location
    - RainLab.Translate
    - RainLab.Pages
    - OFFLINE.Mall 

mail:
    host: smtp.mailgun.org
    name: User Name
    address: email@example.com
    driver: log
```

It's not like it takes super long (thanks to the great documentation!), but just a little perk that would make it even more convenient :)
